### ISSUE TITLE
Please add a screen shot and consider renaming the repository to match the plugin file

### ISSUE THREAD

**Issue by unixorn** [jbugel-lol/custom-made.zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name `zsh` is too generic. Please consider renaming it to something descriptive, or even just name it `oneDark` after the plugin file.

I also prefer to add themes with screen shots in their readme so that users can see what they look like without having to install them.

Thanks!

**Comment by jbugel-lol** [comment]
Hello there @unixorn!
I just want this for private use, so it is my own Theme which i use just for personal use

**Comment by unixorn** [comment]
Ok, I won't add it then.
